### ISSUE TITLE
[Samples/ScanManager] Can't run example

### ISSUE THREAD

**Issue by lebedevich** [urovosamples/SDK_ReleaseforAndroid#3]
Could you help me?

I get this error after running the example (Samples/ScanManager):

![2020-05-07_13-43-32](https://user-images.githubusercontent.com/11410298/81285905-e4eda700-9068-11ea-8176-5fdbd24bc680.png)

**Comment by luisfernandor16** [comment]
I HAVE THE SAME PROBLEM, THERE IS SOME SOLUTION AT PROBLEM?

**Comment by jobhh** [comment]
Are you running this on a compatible Urovo device?
